#pragma once

#include "Renderwerk/Core/Compiler.h"
#include "Renderwerk/Core/CoreAPI.h"
#include "Renderwerk/Core/CoreDefinitions.h"
#include "Renderwerk/Core/Platform.h"
#include "Renderwerk/Core/Memory/Allocators.h"
#include "Renderwerk/Core/Memory/Memory.h"
#include "Renderwerk/Core/Memory/MemoryUnits.h"
#include "Renderwerk/Core/Memory/SmartPointers.h"
#include "Renderwerk/Core/Types/Containers.h"
#include "Renderwerk/Core/Types/String.h"
#include "Renderwerk/Core/Types/StringUtils.h"
#include "Renderwerk/Core/Types/Types.h"
#include "Renderwerk/Core/Types/Delegates/Delegate.h"
#include "Renderwerk/Core/Types/Delegates/MulticastDelegate.h"
