#pragma once

#include <algorithm>
#include <atomic>
#include <cstdint>
#include <functional>
#include <future>
#include <map>
#include <memory>
#include <queue>
#include <ranges>
#include <set>
#include <source_location>
#include <string>
#include <type_traits>
#include <unordered_map>
#include <vector>
#include <xutility>

#include "Renderwerk/Core/Compiler.h"
#include "Renderwerk/Core/CoreAPI.h"
#include "Renderwerk/Core/CoreDefinitions.h"
#include "Renderwerk/Core/Platform.h"
#include "Renderwerk/Core/Memory/Allocators.h"
#include "Renderwerk/Core/Memory/Memory.h"
#include "Renderwerk/Core/Memory/MemoryUnits.h"
#include "Renderwerk/Core/Memory/SmartPointers.h"
#include "Renderwerk/Debug/Profiling.h"
#include "Renderwerk/Engine/Engine.h"
#include "Renderwerk/Jobs/JobSubsystem.h"
#include "Renderwerk/Logging/LogCategory.h"
#include "Renderwerk/Logging/LogManager.h"
#include "Renderwerk/Logging/LogVerbosity.h"
#include "Renderwerk/Platform/Assert.h"
#include "Renderwerk/Platform/ExceptionHandling.h"
#include "Renderwerk/Platform/Guid.h"
#include "Renderwerk/Platform/Platform.h"
#include "Renderwerk/Platform/Windowing/Window.h"
#include "Renderwerk/Platform/Windowing/WindowSubsystem.h"
#include "Renderwerk/Threading/Mutex.h"
#include "Renderwerk/Threading/Signal.h"
#include "Renderwerk/Threading/Thread.h"
#include "Renderwerk/Utils/Timer.h"
