#pragma once

#include "Renderwerk/Graphics/GraphicsCommon.h"

#include <d3d12.h>
#include <d3d12sdklayers.h>
#include <dxgi1_6.h>
#include <dxgidebug.h>
#include <d3dx12/d3dx12.h>

#include <wrl.h>

using Microsoft::WRL::ComPtr;

[[nodiscard]] inline FString D3D12ResultToString(const HRESULT Result)
{
	switch (Result)
	{
	case D3D12_ERROR_ADAPTER_NOT_FOUND: return TEXT("D3D12_ERROR_ADAPTER_NOT_FOUND");
	case D3D12_ERROR_DRIVER_VERSION_MISMATCH: return TEXT("D3D12_ERROR_DRIVER_VERSION_MISMATCH");
	case DXGI_ERROR_ACCESS_DENIED: return TEXT("DXGI_ERROR_ACCESS_DENIED");
	case DXGI_ERROR_ACCESS_LOST: return TEXT("DXGI_ERROR_ACCESS_LOST");
	case DXGI_ERROR_ALREADY_EXISTS: return TEXT("DXGI_ERROR_ALREADY_EXISTS");
	case DXGI_ERROR_CANNOT_PROTECT_CONTENT: return TEXT("DXGI_ERROR_CANNOT_PROTECT_CONTENT");
	case DXGI_ERROR_DEVICE_HUNG: return TEXT("DXGI_ERROR_DEVICE_HUNG");
	case DXGI_ERROR_DEVICE_REMOVED: return TEXT("DXGI_ERROR_DEVICE_REMOVED");
	case DXGI_ERROR_DEVICE_RESET: return TEXT("DXGI_ERROR_DEVICE_RESET");
	case DXGI_ERROR_DRIVER_INTERNAL_ERROR: return TEXT("DXGI_ERROR_DRIVER_INTERNAL_ERROR");
	case DXGI_ERROR_FRAME_STATISTICS_DISJOINT: return TEXT("DXGI_ERROR_FRAME_STATISTICS_DISJOINT");
	case DXGI_ERROR_GRAPHICS_VIDPN_SOURCE_IN_USE: return TEXT("DXGI_ERROR_GRAPHICS_VIDPN_SOURCE_IN_USE");
	case DXGI_ERROR_INVALID_CALL: return TEXT("DXGI_ERROR_INVALID_CALL");
	case DXGI_ERROR_MORE_DATA: return TEXT("DXGI_ERROR_MORE_DATA");
	case DXGI_ERROR_NAME_ALREADY_EXISTS: return TEXT("DXGI_ERROR_NAME_ALREADY_EXISTS");
	case DXGI_ERROR_NONEXCLUSIVE: return TEXT("DXGI_ERROR_NONEXCLUSIVE");
	case DXGI_ERROR_NOT_CURRENTLY_AVAILABLE: return TEXT("DXGI_ERROR_NOT_CURRENTLY_AVAILABLE");
	case DXGI_ERROR_NOT_FOUND: return TEXT("DXGI_ERROR_NOT_FOUND");
	case DXGI_ERROR_REMOTE_CLIENT_DISCONNECTED: return TEXT("DXGI_ERROR_REMOTE_CLIENT_DISCONNECTED");
	case DXGI_ERROR_REMOTE_OUTOFMEMORY: return TEXT("DXGI_ERROR_REMOTE_OUTOFMEMORY");
	case DXGI_ERROR_RESTRICT_TO_OUTPUT_STALE: return TEXT("DXGI_ERROR_RESTRICT_TO_OUTPUT_STALE");
	case DXGI_ERROR_SDK_COMPONENT_MISSING: return TEXT("DXGI_ERROR_SDK_COMPONENT_MISSING");
	case DXGI_ERROR_SESSION_DISCONNECTED: return TEXT("DXGI_ERROR_SESSION_DISCONNECTED");
	case DXGI_ERROR_UNSUPPORTED: return TEXT("DXGI_ERROR_UNSUPPORTED");
	case DXGI_ERROR_WAIT_TIMEOUT: return TEXT("DXGI_ERROR_WAIT_TIMEOUT");
	case DXGI_ERROR_WAS_STILL_DRAWING: return TEXT("DXGI_ERROR_WAS_STILL_DRAWING");
	case E_FAIL: return TEXT("E_FAIL");
	case E_INVALIDARG: return TEXT("E_INVALIDARG");
	case E_OUTOFMEMORY: return TEXT("E_OUTOFMEMORY");
	case E_NOTIMPL: return TEXT("E_NOTIMPL");
	case S_FALSE: return TEXT("S_FALSE");
	case S_OK: return TEXT("S_OK");
	default:
		return TEXT("UNKNOWN");
	}
}
