name: Build and Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: read

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Shipping

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Setup workspace
        shell: pwsh
        run: |
          .\Build\Scripts\Setup.ps1 -Skip-Confirm
      - name: Generate project files
        shell: pwsh
        run: |
          .\Build\Scripts\GenerateProjectFiles.ps1
      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./Binaries/Engine/${{env.BUILD_CONFIGURATION}}
  test:
    needs: [build]
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./Binaries/Engine/${{env.BUILD_CONFIGURATION}}
      - run: ./Binaries/Engine/${{env.BUILD_CONFIGURATION}}/EngineTests.exe
